// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace RaccoonBlog.Web.Controllers
{
    public partial class LegacyPostController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public LegacyPostController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected LegacyPostController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RedirectLegacyPost()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RedirectLegacyPost);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RedirectLegacyArchive()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RedirectLegacyArchive);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public LegacyPostController Actions { get { return MVC.LegacyPost; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "LegacyPost";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "LegacyPost";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string RedirectLegacyPost = "RedirectLegacyPost";
            public readonly string RedirectLegacyArchive = "RedirectLegacyArchive";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string RedirectLegacyPost = "RedirectLegacyPost";
            public const string RedirectLegacyArchive = "RedirectLegacyArchive";
        }


        static readonly ActionParamsClass_RedirectLegacyPost s_params_RedirectLegacyPost = new ActionParamsClass_RedirectLegacyPost();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RedirectLegacyPost RedirectLegacyPostParams { get { return s_params_RedirectLegacyPost; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RedirectLegacyPost
        {
            public readonly string year = "year";
            public readonly string month = "month";
            public readonly string day = "day";
            public readonly string slug = "slug";
        }
        static readonly ActionParamsClass_RedirectLegacyArchive s_params_RedirectLegacyArchive = new ActionParamsClass_RedirectLegacyArchive();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RedirectLegacyArchive RedirectLegacyArchiveParams { get { return s_params_RedirectLegacyArchive; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RedirectLegacyArchive
        {
            public readonly string year = "year";
            public readonly string month = "month";
            public readonly string day = "day";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_LegacyPostController : RaccoonBlog.Web.Controllers.LegacyPostController
    {
        public T4MVC_LegacyPostController() : base(Dummy.Instance) { }

        [NonAction]
        partial void RedirectLegacyPostOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int year, int month, int day, string slug);

        [NonAction]
        public override System.Web.Mvc.ActionResult RedirectLegacyPost(int year, int month, int day, string slug)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RedirectLegacyPost);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "year", year);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "month", month);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "day", day);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "slug", slug);
            RedirectLegacyPostOverride(callInfo, year, month, day, slug);
            return callInfo;
        }

        [NonAction]
        partial void RedirectLegacyArchiveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int year, int month, int day);

        [NonAction]
        public override System.Web.Mvc.ActionResult RedirectLegacyArchive(int year, int month, int day)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RedirectLegacyArchive);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "year", year);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "month", month);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "day", day);
            RedirectLegacyArchiveOverride(callInfo, year, month, day);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108
